# Generated by Django 4.2 on 2024-05-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Имя урока на латинице')),
                ('title', models.CharField(max_length=120, verbose_name='Название урока')),
                ('desc', models.TextField(verbose_name='Описание урока')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('video', models.CharField(max_length=200, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Какой курс?')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
