# Generated by Django 4.0.4 on 2024-05-23 05:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название курса'),
        ),
    ]
