# Generated by Django 4.0.4 on 2024-05-25 23:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_desc_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
